const Icons = {
	borrowed: 'schedule',
	members: 'people',
	books: 'book',
	search: 'search',
	exit: 'logout',
	ebookTH: 'laptop_chromebook',
	add: 'add',
	clear: 'clear',
	cancel: 'clear',
	submit: 'check',
	member: 'person',
	book: 'book',
	name: 'person',
	surname: 'people',
	birthdate: 'date_range',
	phone: 'smartphone',
	home: 'phone',
	address: 'home',
	memberPicture: 'portrait',
	memberCode: '123',
	title: 'title',
	subtitle: 'text_fields',
	author: 'edit',
	publishing: 'publish',
	publishDate: 'date_range',
	publishLocation: 'location_city',
	translator: 'translate',
	ISBN: 'fingerprint',
	bookCode: '123',
	ebook: 'link',
	language: 'language',
	successToast: 'check',
	edit: 'edit',
	delete: 'delete',
	close: 'close',
	openInNew: 'open_in_new',
	formHidden: 'keyboard_arrow_right',
	formActive: 'keyboard_arrow_left',
	confirm: 'check',
	key: 'key',
}

export default Icons
