const Strings = {
	documentTitle: 'Գրադարան',
	headerTitle: 'Գրադարան',
	borrowed: 'Պահ Տրված',
	members: 'Անդամներ',
	books: 'Գրքեր',
	search: 'Որոնել',
	clear: 'Մաքրել',
	add: 'Ավելացնել',
	member: 'Անդամ',
	book: 'Գիրք',
	cancel: 'Չեղարկել',
	submit: 'Հաստատել',
	name: 'Անուն',
	surname: 'Ազգանուն',
	birthdate: 'Ծննդյան Թվական',
	phone: 'Բջջային Համար',
	home: 'Տան Համար',
	address: 'Հասցե',
	memberPicture: 'Պատկեր',
	memberCode: 'Կոդ',
	title: 'Վերնագիր',
	subtitle: 'Խորագիր',
	author: 'Հեղինակ (ներ)',
	publishing: 'Հրատարակչություն',
	publishDate: 'Հրատարակչության Թվական',
	publishLocation: 'Հրատարակչության Վայր',
	translator: 'Թարգմանիչ',
	ISBN: 'ISBN',
	bookCode: 'Կոդ',
	ebook: 'Էլ-Գրքի Հասցե',
	date: 'Թվական',
	deadline: 'Ժամկետ',
	return: 'Վերադարձում',
	hy: 'Հայերեն',
	fa: 'Պարսկերեն',
	en: 'Անգլերեն',
	edit: 'Խմբագրել',
	delete: 'Ջնջել',
	deleteConfirmation: 'Ջնջե՞լ Գրանցումը:',
	close: 'Փակել',
	booksInfo: 'Գրքի Տեղեկություն',
	membersInfo: 'Անդամի Տեղեկություն',
	language: 'Լեզու',
	other: 'Ուրիշ',
}

export default Strings
