const Strings = {
	documentTitle: 'Գրադարան',
	headerTitle: 'Գրադարան',
	borrowed: 'Պահ Տրված',
	members: 'Անդամներ',
	books: 'Գրքեր',
	search: 'Որոնել',
	clear: 'Մաքրել',
	add: 'Ավելացնել',
	member: 'Անդամ',
	book: 'Գիրք',
	cancel: 'Չեղարկել',
	submit: 'Հաստատել',
	name: 'Անուն',
	surname: 'Ազգանուն',
	birthdate: 'Ծննդյան Թվական',
	phone: 'Բջջային Համար',
	home: 'Տան Համար',
	address: 'Հասցե',
	memberPicture: 'Պատկեր',
	memberCode: 'Կոդ',
	title: 'Վերնագիր',
	subtitle: 'Խորագիր',
	author: 'Հեղինակ (ներ)',
	publishing: 'Հրատարակչություն',
	publishDate: 'Հրատարակչության Թվական',
	publishLocation: 'Հրատարակչության Վայր',
	translator: 'Թարգմանիչ',
	ISBN: 'ISBN',
	bookCode: 'Կոդ',
	ebook: 'Էլ-Գրքի Հասցե',
	date: 'Թվական',
	deadline: 'Ժամկետ',
	return: 'Վերադարձում',
	hy: 'Հայերեն',
	fa: 'Պարսկերեն',
	en: 'Անգլերեն',
	edit: 'Խմբագրել',
	delete: 'Ջնջել',
	deleteConfirmation: 'Ջնջե՞լ Գրանցումը:',
	close: 'Փակել',
	booksInfo: 'Գրքի Տեղեկություն',
	membersInfo: 'Անդամի Տեղեկություն',
	language: 'Լեզու',
	other: 'Ուրիշ',
	january: 'հունվար',
	february: 'փետրվար',
	march: 'մարտ',
	april: 'ապրիլ',
	may: 'մայիս',
	june: 'հունիս',
	july: 'հուլիս',
	august: 'օգոստոս',
	september: 'սեպտեմբեր',
	october: 'հոկտեմբեր',
	november: 'նոյեմբեր',
	december: 'դեկտեմբեր',
	memberSelector: 'Ընտրել Անդամ',
	bookSelector: 'Ընտրել Գիրք',
	confirm: 'Հաստատել',
	januaryS: 'հնվ',
	februaryS: 'փտվ',
	marchS: 'մրտ',
	aprilS: 'ապր',
	mayS: 'մյս',
	juneS: 'հնս',
	julyS: 'հլս',
	augustS: 'օգս',
	septemberS: 'սեպ',
	octoberS: 'հոկ',
	novemberS: 'նոյ',
	decemberS: 'դեկ',
	sat: 'շբթ',
	sun: 'կիր',
	mon: 'երկ',
	tue: 'երք',
	wed: 'չրս',
	thu: 'հնգ',
	fri: 'ուր',
	auth: 'Մուտքագրեք Ձեր Գաղտնաբառը:',
	login: 'Մտնել',
	loginTitle: 'Մուտք',
	password: 'Գաղտնաբառ',
}

export default Strings
