const Strings = {
	documentTitle: 'Library',
	headerTitle: 'Library',
	borrowed: 'Borrowed',
	members: 'Members',
	books: 'Books',
	search: 'Search',
	clear: 'Clear',
	add: 'Add',
	member: 'Member',
	book: 'Book',
	cancel: 'Cancel',
	submit: 'Submit',
	name: 'Name',
	surname: 'Surname',
	birthdate: 'Birthday',
	phone: 'Phone',
	home: 'Home',
	address: 'Address',
	memberPicture: 'Picture',
	memberCode: 'Code',
	title: 'Title',
	subtitle: 'Subtitle',
	author: 'Author(s)',
	publishing: 'Publication',
	publishDate: 'Publication Date',
	publishLocation: 'Publication Location',
	translator: 'Translator',
	ISBN: 'ISBN',
	bookCode: 'Code',
	ebook: 'E-Book Link',
	date: 'Borrow Date',
	deadline: 'Deadline',
	return: 'Return Date',
	hy: 'Armenian',
	fa: 'Persian',
	en: 'English',
	edit: 'Edit',
	delete: 'Delete',
	deleteConfirmation: 'Delete this record?',
	close: 'Close',
	booksInfo: 'Book Information',
	membersInfo: 'Member Information',
	language: 'Language',
	other: 'Other',
	january: 'January',
	february: 'February',
	march: 'March',
	april: 'April',
	may: 'May',
	june: 'June',
	july: 'July',
	august: 'August',
	september: 'September',
	october: 'October',
	november: 'November',
	december: 'December',
	memberSelector: 'Select Member',
	bookSelector: 'Select Book',
	confirm: 'Confirm',
	januaryS: 'Jan',
	februaryS: 'Feb',
	marchS: 'March',
	aprilS: 'April',
	mayS: 'May',
	juneS: 'June',
	julyS: 'July',
	augustS: 'Aug',
	septemberS: 'Sep',
	octoberS: 'Oct',
	novemberS: 'Nov',
	decemberS: 'Dec',
	sat: 'Sat',
	sun: 'Sun',
	mon: 'Mon',
	tue: 'Tue',
	wed: 'Wed',
	thu: 'Thu',
	fri: 'Fri',
	auth: 'Please Enter Your Password:',
	login: 'Login',
	loginTitle: 'Login',
	password: 'Password',
}

export default Strings
